language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t yosuke65/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yosuke65/react-test npm test

after_success:
  - docker build -t yosuke65/multi-client ./client
  - docker build -t yosuke65/multi-nginx ./nginx
  - docker build -t yosuke65/multi-server ./server
  - docker build -t yosuke65/multi-worker ./worker
  # Log in to the docekr CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push yosuke65/multi-client
  - docker push yosuke65/multi-nginx
  - docker push yosuke65/multi-server
  - docker push yosuke65/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-470285885149"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
